# Site settings
title: Jumabek Alikahan blog
email: 
description: "Student of Data Science"
baseurl: ""
url: "http://jumabek.github.io"
twitter_username: jumabek_ali
github_username:  jumabek

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
